### ISSUE TITLE
Download Manager: Problem retrieving data

### ISSUE THREAD

**Issue by MarkusMeringer** [ESA-VirES/Aeolus-Client#16]
When clicking "Process and create link" in the Download Manager I get the following message: Error: Problem retrieving data: This process does not allow asynchronous execution!
I did this with the default selection, i.e. called the Download Manager immediately after reset.

**Comment by constantinius** [comment]
Hi @MarkusMeringer, thanks for reporting this

We are currently working on the server side of the download feature, it will be available soon.

**Comment by Weiles** [comment]
I may add some general comments on the Download Manager:

-

**Comment by Weiles** [comment]
I want to add some general comments (mostly minor issues) on the Download Manager:

- For the case when the selected time period exceeds the time span covered by the measurements, the downloaded netCDF file is empty.

- It shall be possible to remove download links which were created within the same session

- The default name of the downloaded file should be identical to the name of the data product (e.g. 'AE_TEST_AUX_MRC......nc'). Additionally, it would be desirable to edit the default name of the download file.

- If possible, it would be good to specify the local saving directory of the files.

- To my eyes, the structure of the netCDF files is very intuitive. In future, it would be helpful to add global attributes to the file which contain a short file description (e.g. AUX_RRC file) and the date when the downloaded file was created. Moreover, local variables attributes which contain the units (as given in the IODD) of the variables could be added.

**Comment by santilland** [comment]
Thank you for the feedback, we have worked on updates to the download functionality.
* All products can be downloaded now (application of filters and selection of custom parameters still need some testing)
* The issue with the empty netCDF should also be solved now, there was an issue of incorrect date parsing in relation to time zones
* As of now it is configured that a user can have two active Download links, this is saved server side. Once a third request is send, the "oldest" download link will be removed from the server. This mechanism was implemented to make sure a user can not use an unlimited amount of storage space on the server. Is there a specific reason for needing manual deletion of a download product?
* The default name has been adapted to use the same format as the original products. We have included "_vires" at the end of the file name suggestion, instead of a version number to help differentiate where the data is coming from.
* This can only be configured by the user in the browser settings, most browsers will show a Save File dialog, (i think) firefox automatically saves everything in the download folder. 
* I created a new ticket #22 to keep track of the idea of adding metadata to the created files

**Comment by Weiles** [comment]
More feedback on the download functionality:

- The selection of custom download parameters for the L1B product causes following error message: "Problem retrieving data: Invalid Input 'fields'!". But it seems to work for AUX-products.

- When changing the granularity of the L1B data product from observation to measurement level, the downloaded file only contains data on observation and not on measurement level.

- Checking the dimensions (sizes) of downloaded L1B observation level parameters showed that the number of observations (672) of the downloaded file exceeds the number of the observations contained in the original ALADIN file (452): 

        <class 'netCDF4._netCDF4.Dataset'>
         root group (NETCDF4 data model, file format HDF5):
         dimensions(sizes): observation(672), array_24(24), array_25(25)
         variables(dimensions):
         groups: observations
 
         vs.
 
         452 observations (1 orbit) in the original file

Further analysis revealed that the downloaded parameters are masked arrays (I opened the netCDF files in Python) where the number of the non-masked array elements corresponds to the "correct" number of observations. For my case, it was 336 observations as I downloaded a subset of one Orbit. I wonder why the downloaded file contains twice the number of observations.

**Comment by santilland** [comment]
Thank you for your feedback, i updated the client on the staging environment with some improvements.
* The selection of custom parameters now works also for L1B products (there is an issue with measurement parameters we are working on)
* The granularity level is now also shown in the download panel and depending on the selected granularity it will show only related custom parameters for selection and if no custom parameters are selected it will request all parameters that have the selected granularity (as mentioned before taking into account the issue with downloading of measurement granularity products)
* I have been also comparing dimension between original data and downloaded data and in my case it seems there is a difference of 1 observation from 450 in the original to 449 in the generated file. I think this could have to do with an exclusive comparison of time were one value could be getting lost.
The generated product uses exactly the selected time, meaning that if you selected a period that spans over two products it merges the data of both into one file. Could you look at the process detail information and send it to me to try to replicate your result?

**Comment by santilland** [comment]
I will close this issue now, the download functionality has also further evolved and i think it is no longer relevant.
