### ISSUE TITLE
Minor issues on staging service update from July 18, 2018 

### ISSUE THREAD

**Issue by Weiles** [ESA-VirES/Aeolus-Client#18]
Some very minor issues:

- In the same way as for the L1B data product, it would be desirable to visualise the flight direction of the satellite also for AUX_files.

- The area selection is not working for AUX_files (the time selection does).

- Saving png-pictures for the Analytics View plot panels: It would be clearer if the names of the browser windows were named like: "Opening download upper Panel" and "Opening download lower panel". If possible, it also would be good to specifiy the name of the picture.

- Infobox for single values contained in the AUX files: To me, a columnar structure of the information would be more user-friendly: | Parameter Name | Value | Unit |

**Comment by santilland** [comment]
I responded to some of the points by mail but in order to better keep track i will also answer here.
* I created a new issue for visualization of flight path for aux data here #20 (it is easier to manage them apart).
* The area selection has been implemented also for AUX data
* I am not sure i understand the point, i also created a new ticket here #21 to keep track of things separately
* The infobox for single values has been updated to show a table based structure including where available the unit.

I consider the points described either solved or handled in separate issues, i will close the ticket in some time if there are no other comments.
