### ISSUE TITLE
L1B problems in retrieving "measurements" data 

### ISSUE THREAD

**Issue by paoladaulerio** [ESA-VirES/Aeolus-Client#67]
Trying to visualise L1b products in measurements granularity the system in most cases returns an error message "problem retrieving data:index 0 is out of bounds for axis 0 with size 0". This is not systematic even for the same product, but at a first investigation it happens when the time selection is changed

**Comment by santilland** [comment]
Investigating the problem we have found that this can happen when there is a gap in the product and a time interval is selected which contains no data, we will update this to just show that there is no data in the current selection (instead of an error).
In your case though it seems to happen more often (we have not found many products with gaps). Are you testing on the production or staging environment?
Can you just in case make sure to clean the browser cache and reset the workspace? If there is still a problem occurring could you please provide some time intervals where the issue appears?

**Comment by paoladaulerio** [comment]
The test is done on the production environment and the selected products do not show any gap. Anyhow doing some additional test I have realised that the problem occurs sistematically only when the product  is selected by clicking above the product on the time-line  while when the selection  is done dragging the grey area the same data are loaded correctly. This occurrence is only for measurement while for observation it works in any case

**Comment by santilland** [comment]
Ah, that is the issue, i imagine it tries to access information of the "surrounding" product and after applying the time filter there are no elements left and it tries to access the empty element, we will introduce a check for that. Thank you!

**Comment by santilland** [comment]
An additional check has been implemented and deployed on the staging environment.
This fixes the issue.

**Comment by santilland** [comment]
This issue was solved, closing the ticket.
