### ISSUE TITLE
uploaded L2A products 

### ISSUE THREAD

**Issue by paoladaulerio** [ESA-VirES/Aeolus-Client#75]
I have tried to upload a L2A product ( on the Staging) and the "_user" and "_diff" parameters look not available

**Comment by santilland** [comment]
I was able to reproduce the issue, there have been some minor changes in how data is handled i will check for the issue.

**Comment by santilland** [comment]
I think the issue is when clicking on a product on the time slider (as there is some overlap with neighboring products) the amount of values returned for the "original" data (selected range) is different from the uploaded file (which has no neighbours) and there is no trivial way of knowing which value is combined to which. 
Could you try selecting a range "inside" of one of the product to see if you get the user and diff values?

**Comment by paoladaulerio** [comment]
yes, just tried and actually selecting a range inside I can see also the _diff and _user. 
I have also noted that even if I select L1B product from Layer  I can see on the time slider also the updated L2A file.  Probably this needs to also be corrected

**Comment by santilland** [comment]
I implemented only showing user uploaded data when the same collection is active (needs to be deployed to staging). Still i am unsure how to handle the issue of overlapping data.
Would reducing the interval time selection a little when clicking on a product be ok?
This should also "increase performance" as usually only one product would be "touched/read" in order to create the response instead of the possible 3 (counting both neighbors).

**Comment by paoladaulerio** [comment]
I was thinking about it. What is weird for me is that in an identical (apparently) case the behaviour is different. In both the tests I have done (with two different products) the uploaded file has exactly same duration (according to the filename) than the "original" but in the first test even clicking on the time slider I am able to  see the parameters in the uploaded file and in second no. Anyway there will be an explanation, of course I don't know in deep the logic or complexity which is behind. I was wondering if it is just occasional or rather sistematic ... 
Regarding your proposal, if I well understand the visualized time range will be a little bit smaller of the real time duration of the uploaded product, is it correct? This is ok as a workaround to be back on the topic in the future, if it needs. I think this feature can be of interest more for the processors  developers (to compare two files from different versions) and they could have different needs.

**Comment by santilland** [comment]
I think the issue appears every time the original file that is going to be compared has an overlap either at the beginning or the end of the product with the previous or the next product.
In that case comparison is not done because the returned structure is different then the one the user is trying to compare to. For example maybe one more measurement, and the mapping of which to which is no longer clear.
At least i think this is what is happening. By reducing a little bit the begin and end time when clicking on a product this overlap and possible difference in structure should not happen.
I will try out this solution.

**Comment by santilland** [comment]
Ok, i added a 1 minute delta which is subtracted from the time interval (start and end).
It seems the typical overlap is about ~20 to 30 seconds, so that should be enough.
Will need to do some more tests.

**Comment by paoladaulerio** [comment]
Test done, it works. Thanks
